import type { Loan, LoanEvent, MarketSnapshot, TicketCollateralNote } from "./types";

const now = new Date("2026-06-06T17:00:00-04:00");

export const demoMarketSnapshot: MarketSnapshot = {
  dcrUsd: 12.13,
  dcrBtc: 0.00019937,
  krakenBid: 12.081,
  krakenAsk: 12.102,
  dcrdexBestBid: 20040,
  dcrdexBestAsk: 20100,
  dcrdexStableBookEmpty: true,
  sourceCount: 4,
  stale: false,
  warnings: [
    "DCRDEX DCR/USDC and DCR/USDT books were empty during research, so liquidation automation stays review-gated.",
    "No mainnet keys are used in this app.",
  ],
  updatedAt: now.toISOString(),
};

export const demoLoans: Loan[] = [
  {
    id: "loan_demo_active",
    ref: "DCR-7421",
    borrowerName: "Demo borrower",
    lenderName: "Demo treasury",
    status: "active",
    collateralDcr: 110,
    collateralUsd: 1334.3,
    borrowAsset: "USDC",
    borrowAmount: 390,
    initialLtvBps: 2923,
    currentLtvBps: 2960,
    aprBps: 1450,
    termDays: 30,
    escrowAddress: "DsDemo2of3EscrowActive9xWzQbTnR",
    redeemScript: "522102borrower2102lender2102arbiter53ae",
    borrowerPubkey: "02borrower-demo-public-key-active",
    lenderPubkey: "02lender-demo-public-key-active",
    arbiterPubkey: "02arbiter-demo-public-key-active",
    depositTxid: "dcr-demo-collateral-tx-active",
    payoutTxid: "base-sepolia-demo-usdc-payout-active",
    repaymentTxid: null,
    dueAt: new Date(now.getTime() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: now.toISOString(),
    ticketProofStatus: "not_used",
  },
  {
    id: "loan_demo_pending",
    ref: "DCR-9184",
    borrowerName: "Hardware-wallet borrower",
    lenderName: "Demo treasury",
    status: "awaiting_collateral",
    collateralDcr: 75,
    collateralUsd: 909.75,
    borrowAsset: "USDC",
    borrowAmount: 250,
    initialLtvBps: 2748,
    currentLtvBps: 2748,
    aprBps: 1450,
    termDays: 14,
    escrowAddress: "DsDemo2of3EscrowPending3bKqM8x",
    redeemScript: "522102borrower2102lender2102arbiter53ae",
    borrowerPubkey: "02borrower-demo-public-key-pending",
    lenderPubkey: "02lender-demo-public-key-pending",
    arbiterPubkey: "02arbiter-demo-public-key-pending",
    depositTxid: null,
    payoutTxid: null,
    repaymentTxid: null,
    dueAt: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    ticketProofStatus: "not_used",
  },
  {
    id: "loan_demo_ticket_research",
    ref: "DCR-3030",
    borrowerName: "Ticket holder",
    lenderName: "Research desk",
    status: "draft_quote",
    collateralDcr: 0,
    collateralUsd: 0,
    borrowAsset: "USDC",
    borrowAmount: 0,
    initialLtvBps: 0,
    currentLtvBps: 0,
    aprBps: 0,
    termDays: 0,
    escrowAddress: "Research only: no escrow created",
    redeemScript: "Research only: existing tickets are not liquid collateral",
    borrowerPubkey: "n/a",
    lenderPubkey: "n/a",
    arbiterPubkey: "n/a",
    depositTxid: null,
    payoutTxid: null,
    repaymentTxid: null,
    dueAt: now.toISOString(),
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    ticketProofStatus: "verified_exposure",
  },
];

export const demoEvents: LoanEvent[] = [
  {
    id: "evt_1",
    loanId: "loan_demo_active",
    type: "collateral_confirmed",
    message: "110 DCR demo collateral reached the confirmation threshold.",
    actor: "system",
    createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt_2",
    loanId: "loan_demo_active",
    type: "funded",
    message: "390 demo USDC was sent to the borrower destination.",
    actor: "operator",
    createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000 + 900000).toISOString(),
  },
  {
    id: "evt_3",
    loanId: "loan_demo_pending",
    type: "escrow_created",
    message: "2-of-3 Decred escrow instructions are ready for the borrower.",
    actor: "system",
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt_4",
    loanId: "loan_demo_ticket_research",
    type: "ticket_research",
    message: "Existing ticket proof can show staking exposure, but it is not secure collateral in v1.",
    actor: "system",
    createdAt: now.toISOString(),
  },
];

export const ticketCollateralNote: TicketCollateralNote = {
  status: "research_only",
  title: "Ticket collateral is promising, but not v1 collateral",
  summary:
    "A live Decred ticket proves locked stake and voting exposure, but the lender cannot liquidate it while the ticket is live. The MVP should only display ticket proofs as research context.",
  blocker:
    "A ticket cannot be canceled and proceeds only return after vote, miss, expiry, and required maturity/revocation behavior.",
  nextValidation:
    "Use simnet to test whether a newly purchased ticket can direct refund and reward proceeds into an escrow-controlled path without breaking voting.",
};
